In [30]:
# package imports
import pandas as pd
import numpy as np 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import matplotlib.pyplot as plt
%matplotlib inline

import tensorflow as tf
from tensorflow import keras

# 数据
数值（主要用这个）、字符串、布尔

## 数值类型

In [16]:
num = tf.constant(1.2)
num
num = tf.constant([1,2.,3.3])
num

str = tf.constant('maowei')
str

boo = tf.constant(True)
boo

<tf.Tensor: id=25, shape=(), dtype=float32, numpy=1.2>

<tf.Tensor: id=26, shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

<tf.Tensor: id=27, shape=(), dtype=string, numpy=b'maowei'>

<tf.Tensor: id=28, shape=(), dtype=bool, numpy=True>

## 类型转换

## 数据操作

### 创建

In [18]:
tf.random.uniform([5],maxval=100,dtype=tf.int32)

<tf.Tensor: id=36, shape=(5,), dtype=int32, numpy=array([94, 53, 50, 58, 82], dtype=int32)>

In [21]:
from tensorflow.keras import layers # 导入层模块
x = tf.random.normal([4,28*28])
# 创建全连接层，指定输出节点数和激活函数
fc = layers.Dense(512, activation=tf.nn.relu)
h = fc(x)
fc.variables

[<tf.Variable 'dense_2/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[ 0.04984554,  0.04712541,  0.03975577, ...,  0.02985692,
         -0.05768434, -0.01323285],
        [-0.06009118,  0.0496932 ,  0.0340799 , ..., -0.01568665,
          0.02476484, -0.011956  ],
        [ 0.0121459 , -0.0022179 , -0.06405416, ...,  0.01963593,
         -0.04445248,  0.00130545],
        ...,
        [ 0.02898338,  0.00032837, -0.01014856, ...,  0.02102096,
         -0.01813108,  0.02801073],
        [ 0.05427015, -0.03215735, -0.05066388, ..., -0.05369793,
         -0.01244892,  0.03419153],
        [-0.04729349,  0.02228568, -0.05532363, ..., -0.0495715 ,
         -0.04757553,  0.05096141]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [23]:
z = tf.constant([1.,1.,1.])
tf.nn.softmax(z)

<tf.Tensor: id=142, shape=(3,), dtype=float32, numpy=array([0.33333334, 0.33333334, 0.33333334], dtype=float32)>

In [25]:
y_onehot = tf.constant([1,3]) # 构造真实值
y_onehot = tf.one_hot(y_onehot, depth=10)
y_onehot

<tf.Tensor: id=152, shape=(2, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [29]:
A = tf.random.uniform([32,1],maxval=10,dtype=tf.int32)# 创建矩阵
A
B =  tf.broadcast_to(A, [2,32,4])# 扩展为 4D 张量
B

<tf.Tensor: id=173, shape=(32, 1), dtype=int32, numpy=
array([[3],
       [7],
       [0],
       [0],
       [2],
       [7],
       [5],
       [7],
       [8],
       [2],
       [4],
       [4],
       [6],
       [6],
       [5],
       [9],
       [1],
       [7],
       [1],
       [7],
       [3],
       [1],
       [1],
       [5],
       [1],
       [4],
       [1],
       [2],
       [8],
       [7],
       [3],
       [5]], dtype=int32)>

<tf.Tensor: id=175, shape=(2, 32, 4), dtype=int32, numpy=
array([[[3, 3, 3, 3],
        [7, 7, 7, 7],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [2, 2, 2, 2],
        [7, 7, 7, 7],
        [5, 5, 5, 5],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [2, 2, 2, 2],
        [4, 4, 4, 4],
        [4, 4, 4, 4],
        [6, 6, 6, 6],
        [6, 6, 6, 6],
        [5, 5, 5, 5],
        [9, 9, 9, 9],
        [1, 1, 1, 1],
        [7, 7, 7, 7],
        [1, 1, 1, 1],
        [7, 7, 7, 7],
        [3, 3, 3, 3],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [5, 5, 5, 5],
        [1, 1, 1, 1],
        [4, 4, 4, 4],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [8, 8, 8, 8],
        [7, 7, 7, 7],
        [3, 3, 3, 3],
        [5, 5, 5, 5]],

       [[3, 3, 3, 3],
        [7, 7, 7, 7],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [2, 2, 2, 2],
        [7, 7, 7, 7],
        [5, 5, 5, 5],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [2, 2, 2, 2],
        [4, 4, 4

# kears接口

In [31]:
from tensorflow.keras import layers, Sequential

In [34]:
network = Sequential([ # 封装为一个网络

layers.Dense(3, activation=None), # 全连接层，此处不使用激活函数

layers.ReLU(),#激活函数层

layers.Dense(2, activation=None), # 全连接层，此处不使用激活函数

layers.ReLU() #激活函数层

])

network.build(input_shape=(4, 4))
network.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              multiple                  15        
_________________________________________________________________
re_lu_4 (ReLU)               multiple                  0         
_________________________________________________________________
dense_8 (Dense)              multiple                  8         
_________________________________________________________________
re_lu_5 (ReLU)               multiple                  0         
Total params: 23
Trainable params: 23
Non-trainable params: 0
_________________________________________________________________
